from __future__ import annotations

import json
import re
from typing import Any

from wellmanifest.models import Diagnostic, Document, DocumentMetadata, Severity

from .base import Dialect, DialectError
from .common import split_runtime_prelude
from .json_dialect import JsonDialect


class TypeScriptDialect(Dialect):
    """Restricted TypeScript data module dialect.

    The runtime intentionally accepts only a deterministic subset generated by
    WellManifest: an ``export default`` JSON object optionally followed by
    ``as const`` and ``satisfies <Type>``.  It does not execute JavaScript and it
    is not a general TypeScript parser.
    """

    name = "typescript@wellm-1"
    aliases = (
        "typescript",
        "ts",
        "application/typescript",
        "text/typescript",
        "application/wellmanifest+typescript",
    )
    media_types = (
        "application/typescript",
        "text/typescript",
        "application/wellmanifest+typescript",
    )
    extensions = (".wm.ts", ".wellm.ts", ".manifest.ts")

    def parse(self, source: str, *, source_name: str | None = None) -> Document:
        cleaned, directives = split_runtime_prelude(source)
        object_text = self._extract_exported_json_object(cleaned)
        try:
            data: Any = json.loads(object_text)
        except json.JSONDecodeError as exc:
            raise DialectError(
                "WM-TS-001",
                "TypeScript import accepts only the canonical WellManifest JSON-object subset: "
                f"{exc.msg}",
                line=exc.lineno,
                column=exc.colno,
            ) from exc
        if not isinstance(data, (dict, list)):
            raise DialectError("WM-TS-002", "The exported TypeScript value must be an object or array")
        metadata = DocumentMetadata(
            source_dialect=self.name,
            document_kind=directives.get("kind", "data"),
            schema_ref=directives.get("schema"),
            schema_dialect="json-schema@2020-12" if directives.get("schema") else None,
            source_name=source_name,
            directives=directives,
        )
        diagnostics = [
            Diagnostic(
                code="WM-TS-100",
                severity=Severity.INFO,
                phase="parse",
                dialect=self.name,
                source=source_name,
                message="Parsed the safe WellManifest TypeScript object-literal subset; arbitrary code was not executed.",
            )
        ]
        return Document(
            metadata=metadata,
            data=data,
            ir={"kind": "data", "value": data, "typescriptSubset": "export-default-json@1"},
            diagnostics=diagnostics,
            source_text=source,
        )

    def emit(self, document: Document, *, projection: str = "data", pretty: bool = True) -> str:
        value = document.data if projection == "data" else JsonDialect._ir_projection(document)
        if not isinstance(value, (dict, list)):
            raise ValueError("TypeScript emission requires an object or array root")
        rendered = json.dumps(
            value,
            ensure_ascii=False,
            indent=2 if pretty else None,
            separators=None if pretty else (",", ":"),
        )
        header = (
            "// Generated by wellm. This is a data module, not executable configuration logic.\n"
            "export type WellManifestDocument = Readonly<Record<string, unknown>> | readonly unknown[];\n\n"
        )
        return f"{header}export default {rendered} as const satisfies WellManifestDocument;\n"

    def probe(self, source: str, *, source_name: str | None = None) -> float:
        if source_name and source_name.lower().endswith(self.extensions):
            return 0.96
        if re.search(r"\bexport\s+default\s*[\[{]", source) and (
            "satisfies WellManifestDocument" in source or "Generated by wellm" in source
        ):
            return 0.94
        return 0.0

    @classmethod
    def _extract_exported_json_object(cls, source: str) -> str:
        match = re.search(r"\bexport\s+default\s*", source)
        if not match:
            raise DialectError("WM-TS-003", "Expected `export default` in the TypeScript data module")
        start = cls._skip_space_and_comments(source, match.end())
        if start >= len(source) or source[start] not in "[{":
            raise DialectError("WM-TS-004", "`export default` must be followed by a JSON object or array")
        opener = source[start]
        closer = "}" if opener == "{" else "]"
        stack = [closer]
        in_string = False
        escaped = False
        index = start + 1
        while index < len(source):
            char = source[index]
            if in_string:
                if escaped:
                    escaped = False
                elif char == "\\":
                    escaped = True
                elif char == '"':
                    in_string = False
                index += 1
                continue
            if char == '"':
                in_string = True
            elif char in "[{":
                stack.append("}" if char == "{" else "]")
            elif char in "]}":
                if not stack or char != stack[-1]:
                    raise DialectError("WM-TS-005", "Unbalanced object literal in TypeScript module")
                stack.pop()
                if not stack:
                    return source[start : index + 1]
            index += 1
        raise DialectError("WM-TS-006", "Unterminated object literal in TypeScript module")

    @staticmethod
    def _skip_space_and_comments(source: str, index: int) -> int:
        while index < len(source):
            if source[index].isspace():
                index += 1
                continue
            if source.startswith("//", index):
                newline = source.find("\n", index + 2)
                return len(source) if newline == -1 else TypeScriptDialect._skip_space_and_comments(source, newline + 1)
            if source.startswith("/*", index):
                end = source.find("*/", index + 2)
                if end == -1:
                    raise DialectError("WM-TS-007", "Unterminated TypeScript comment")
                index = end + 2
                continue
            break
        return index
